name: Workflow Staging
on:
  push:
      branches:
        - main
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{ secrets.APP_NAME }}
          heroku_email: "louisandrew3@gmail.com"
          usedocker: true
          docker_build_args: |
            APP_NAME
            SECRET_KEY
            REMOTE
        env: 
          APP_NAME: ${{ secrets.APP_NAME }}
          SECRET_KEY: ${{secrets.SECRET_KEY}}
          REMOTE: 1
  create-release-pr:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 0
      - name: generate-pr
        uses: devops-infra/action-pull-request@v0.4.2
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          source_branch: main
          target_branch: production
          title: "[Release]: ${{github.event.commits[0].message}}"
          body: "## Automated PR by GitHub action\n"
          get_diff: true
          ignore_users: "dependabot"
     